version: "3.6"
services:
  api3:
    image: web3labs/epirus-free-api:latest
    restart: always
    hostname: api3
    environment:
      - NODE_ENDPOINT=http://besu_node3:8545
      - MONGO_CLIENT_URI=mongodb://mongodb3:27017
      - REINDEX_ENDPOINT=http://ingestion3/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
      - REDIS_HOST=redis3
      - REDIS_PORT=6379
    depends_on:
      - redis3 
      - mongodb3
    networks:
      besu_network:
  
  mongodb3:
    image: mongo:5.0.8
    restart: always
    hostname: mongodb3
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      besu_network:

  redis3:
    image: redis
    restart: always
    hostname: redis3
    container_name: redis3
    networks:
      besu_network:

  web3:
    image: web3labs/epirus-free-web:latest
    restart: always
    hostname: web3
    environment:
      - API_URL=/api
      - DISPLAY_NETWORK_TAB=true
    depends_on:
      - api3
    networks:
      besu_network:
  
  ingestion3:
    image: web3labs/epirus-free-ingestion:latest
    restart: always
    hostname: ingestion3
    environment:
      - NODE_ENDPOINT=http://besu_node3:8545
      - MONGO_CLIENT_URI=mongodb://mongodb3:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb3
    networks:
      besu_network:

  chainlens3:
    image: nginx:latest
    restart: always
    hostname: chainlens3
    volumes:
      - ./nginx3.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 80:80
    depends_on:
      - api3
      - web3
    networks:
      besu_network:
        

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true


