version: "3.6"
services:
  api2:
    image: web3labs/epirus-free-api:latest
    restart: always
    hostname: api2
    environment:
      - NODE_ENDPOINT=http://besu_node2:8545
      - MONGO_CLIENT_URI=mongodb://mongodb2:27017
      - REINDEX_ENDPOINT=http://ingestion2/reindex/
      - MONGO_DB_NAME=epirus
      - MONGO_CREATE_INDICES=true
      - REDIS_HOST=redis2
      - REDIS_PORT=6379
    depends_on:
      - redis2 
      - mongodb2
    networks:
      besu_network:
  
  mongodb2:
    image: mongo:5.0.8
    restart: always
    hostname: mongodb2
    environment:
      - COMPOSE_HTTP_TIMEOUT=900
      - DOCKER_CLIENT_TIMEOUT=900
    entrypoint: mongod --bind_ip "0.0.0.0"
    networks:
      besu_network:

  redis2:
    image: redis
    restart: always
    hostname: redis2
    container_name: redis2
    networks:
      besu_network:

  web2:
    image: web3labs/epirus-free-web:latest
    restart: always
    hostname: web2
    environment:
      - API_URL=/api
      - DISPLAY_NETWORK_TAB=true
    depends_on:
      - api2
    networks:
      besu_network:
  
  ingestion2:
    image: web3labs/epirus-free-ingestion:latest
    restart: always
    hostname: ingestion2
    environment:
      - NODE_ENDPOINT=http://besu_node2:8545
      - MONGO_CLIENT_URI=mongodb://mongodb2:27017
      - MONGO_DB_NAME=epirus
    depends_on:
      - mongodb2
    networks:
      besu_network:

  chainlens2:
    image: nginx:latest
    restart: always
    hostname: chainlens2
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
      - ./5xx.html:/www/error_pages/5xx.html
    ports:
      - 80:80
    depends_on:
      - api2
      - web2
    networks:
      besu_network:
        

networks:
  besu_network:
    name: besu_network
    driver: overlay
    external: true


